apiVersion: 1

datasources:
  - name: Doris
    type: mysql
    access: proxy
    url: doris:9030
    database: industrial_apm
    user: root
    uid: apm-doris
    editable: true
    jsonData:
      timeInterval: "5s"
